### ISSUE TITLE
Error on Client Launch

### ISSUE THREAD

**Issue by spiffynacho** [AnchyDev/BreakingNewsOverride#10]
Upon patching AzerothCore with the latest updates, I am seeing this error:
[string "local a=ServerAlertFrame;local b=ServerAlertText;local c=Server..."]: 1: ')' expected near 's"
![image](https://github.com/AnchyDev/BreakingNewsOverride/assets/55950024/322ed640-15b9-478d-ad92-91b972c62c76)
The Breaking News panel does not appear, only this error.  The game functions fine once OK is clicked.  I can disable the mod and the error disappears.

**Comment by AnchyDev** [comment]
It's possible the entire payload was not transmitted or your breaking news html is not valid. Can you share your breaking news html?

**Comment by spiffynacho** [comment]
> It's possible the entire payload was not transmitted or your breaking news html is not valid. Can you share your breaking news html?

Here's the contents of the index.html file I was using:

<html><body>
<img src="wow.jpg" width="32" height="32" align="center"/><br/>
<h2>Vote For Us!</h2>
<p>Please vote for our server at <a href="https://topg.org/wow-private-servers/server-659002">TOPG.ORG</a>.  You can vote daily and it helps boost our ranking on their list of servers.</p><br/>
<h2>First Level 80!</h2>
<p>Congrats to Shade, the server's first level 80 character!</p><br/>
<h2>Discord Server</h2>
<p>Join our Discord server by <a href="https://discord.gg/6VbAewZV">clicking here</a>.</p><br/>
<h2>Weekly Maintenance</h2>
<p>The scheduled maintenance window is Sunday mornings from approximately 4:00-7:00 AM CST.</p>
</body></html>

It was working fine prior to the latest AC patches.

**Comment by AnchyDev** [comment]
At first glance that looks fine, I'm unsure of the problem and I don't see any recent commits to AC that should affect how the payload manager works.

**Comment by AnchyDev** [comment]
Just to update everybody, I don't know how I missed it but this is not valid HTML for this module. All single quotes should be escaped to perform correct.

This is the HTML fixed:
```html
<html><body>
<img src="wow.jpg" width="32" height="32" align="center"/><br/>
<h2>Vote For Us!</h2>
<p>Please vote for our server at <a href="https://topg.org/wow-private-servers/server-659002">TOPG.ORG</a>.  You can vote daily and it helps boost our ranking on their list of servers.</p><br/>
<h2>First Level 80!</h2>
<p>Congrats to Shade, the server\'s first level 80 character!</p><br/>
<h2>Discord Server</h2>
<p>Join our Discord server by <a href="https://discord.gg/6VbAewZV">clicking here</a>.</p><br/>
<h2>Weekly Maintenance</h2>
<p>The scheduled maintenance window is Sunday mornings from approximately 4:00-7:00 AM CST.</p>
</body></html>
```
