### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by Tony931023** [AnchyDev/BreakingNewsOverride#3]
In file included from /mnt/hdd/amanthul-azerothcore-wotlk/modules/BreakingNewsOverride/src/BreakingNews.cpp:5:
/mnt/hdd/amanthul-azerothcore-wotlk/modules/BreakingNewsOverride/src/BreakingNews.h:35:45: fatal error: unknown type name 'WardenPayloadMgr'
    void SendChunkedPayload(Warden* warden, WardenPayloadMgr* payloadMgr, std::string payload, uint32 chunkSize);
                                            ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:76: modules/CMakeFiles/modules.dir/BreakingNewsOverride/src/BreakingNews.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1218: modules/CMakeFiles/modules.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by AnchyDev** [comment]
Ensure you have updated to the latest version of AzerothCore to be able to use the Payload manager that this module uses.

**Comment by Tony931023** [comment]
Yes exactly, I had noticed later on the discord, I already updated everything perfect
